name: "CI - Code Analysis"

on:
  pull_request:
    branches:
      - main

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: "composer:v2"

      - name: "Install dependencies"
        run: composer install --no-progress --no-interaction --quiet

      - name: "PHPStan analysis"
        run: vendor/bin/phpstan analyse
