name: "CI - Code Style"

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: "Install PHP CodeSniffer"
        run: curl -OL https://phars.phpcodesniffer.com/phpcs.phar

      - name: "Run PHP CodeSniffer"
        uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
